version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=p@$$w0rd123
  redis:
    image: redis:latest
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - '80:80'
  api:
    build:
      context: ./api/
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules/
      - ./api:/app/
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPORT=5432
      - PGPASSWORD=p@$$w0rd123
  worker:
    build:
      context: ./worker/
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules/
      - ./worker:/app/
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  client:
    build:
      context: ./complex-client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules/
      - ./complex-client:/app
