apiVersion: apps/v1
kind: Deployment
metadata:
  name: complex-api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
        - name: api
          image: ajduet/complex-api
          ports:
            - containerPort: 5000
          resources:
            limits:
              memory: '128Mi'
              cpu: '250m'
          env:
            - name: REDIS_HOST
              value: redis-cluster-service
            - name: REDIS_PORT
              value: '6379'
            - name: PGUSER
              value: 'postgres'
            - name: PGDATABASE
              value: 'postgres'
            - name: PGPORT
              value: '5432'
            - name: PGHOST
              value: postgres-cluster-service
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD
